apiVersion: v1
kind: Template
metadata:
  name: nexus-kamil
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      app: nexus3
    name: nexus3
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: sonatype/nexus3:latest
      from:
        kind: DockerImage
        name: docker.io/sonatype/nexus3:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: nexus-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: nexus3
    name: nexus3
  spec:
    paused: false
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: nexus3
      deploymentconfig: nexus3
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      recreateParams:
        timeoutSeconds: 100
        post:
          failurePolicy: Abort
          execNewPod:
            containerName: nexus3
            command:
              - "/bin/bash"
              - "-c"
              - "curl -s https://raw.githubusercontent.com/wkulhanek/ocp_advanced_development_resources/master/nexus/setup_nexus3.sh | bash -s admin admin123 http://nexus3:8081"
      type: Recreate
    template:
      metadata:
        labels:
          app: nexus3
          deploymentconfig: nexus3
      spec:
        containers:
        - image: sonatype/nexus3:latest
          imagePullPolicy: Always
          name: nexus3
          ports:
          - containerPort: 8081
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /repository/maven-public/
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus3-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nexus3-volume-1
          persistentVolumeClaim:
            claimName: nexus-pvc
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nexus3
        from:
          kind: ImageStreamTag
          name: nexus3:latest
          namespace: 1eb0-nexus
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: nexus3-registry
  spec:
    ports:
    - name: docker-registry
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      name: nexus3
    sessionAffinity: ClientIP
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nexus3
    name: nexus3
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus3
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: nexus3-registry
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: nexus3-registry
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: nexus3
    name: nexus3
  spec:
    to:
      kind: Service
      name: nexus3
      weight: 100
    wildcardPolicy: None
